var language = {};
language.en = {
	TITLE:"Router",
	//按钮
	SPAN:{
		country_tip:"Please strictly abide by local laws and be cautious in using them.",
		linkQ_text:"Link Quality",
		tx_rate_text:"Tx Rate",
		rx_rate_text:"Rx Rate",
		tx_put_text:"Tx throughput",
		rx_put_text:"Rx throughput",
		sta_user_txt:"User name",
		sta_pwd_txt:"Password",
		check_time_txt:"Synchronous mode",
	    set_custom:"Manual Setup",
		flow_care_text:'In the procedure of signal tracking,  the unexpectable effects probably occur in Tx/Rx data transaction. Please press "Stop Tracking" button instantly after signal tracking.',
		third_sys_flow:"Signal tracking",
		third_sys_flow_tit:"Signal tracking",
		flow_sta:"track status",
		set_ONEKEY:"Onekey AiConnect",
		
		Auth_key:"Auth key",
		Auth_port:"Auth port",
		Auth_server:"Auth server",
	
		third_wrl2_wds_status:"Super WDS settings",
		lbl_wireless_status_wds:"Super WDS state",
		lbl_key_len:"Key length",
		lbl_key_g:"Key format",
		bit64:"Wep 64 bit",
		bit128:"Wep 128 bit",
		wds_one_wds:"First:WDS Settings",
		third_status_wireless2_wds:"Super WDS state",
		mode_wds_text:"Super WDS",
		
		port_title:"port",
		protocol_title:"protocol",
		protocol:"protocol",
		sorry:"sorry！",
		text1:"The firmware in the device is not valid,",
		text2:"Please upgarde a valid firmware.",
		notes_file:"*Note: In the process of upgrading, please keep the device power on, otherwise the firmware may be corrupted!",
		se_notes:"ALL",
		
		ddns_notes:"Need to restart the device to take effect",
		
		cpu_df:"CPU Frequency:550MHz",
		version_login:"Software Version",
		photo_span_text:"Welcome User",
		system_status_font:"Status",
		fast_setting_font:"Wizard",
		advanced_settings_font:"Advanced",
		set_exit:"Exit",
		system_mode_title:"Mode",
		main_restart:"Reboot",
		tai:" ",
		adv_text_time:"Running time",
		adv_software_version:"Software Version",
		status_ap_name:"name",
		status_ap_dev:"position",
		status_br_bssid:"BSSID",
		channel_name:"channel",
		wrl24_off_text:"Wireless off",
		wrl58_off_text:"5.8G WLAN off",
		br_off_text:"Relay connection off",
		status_wrl_bssid:"BSSID",
		
		wifi_channel_wrl2:"2.4Gwifi Channel analysis",
		wifi_channel_wrl5:"5.8Gwifi Channel analysis",
		
		set_window_wrl2:"Wireless settings",
		set_window_wrl5:"5.8G Wireless settings",
		set_window_lan:"LAN settings",
		
		title_cpu_txt:"CPU usage",
		title_wrl2_txt:"Wireless settings",
		title_wrl5_txt:"5.8G Wireless settings",
		title_lan_txt:"LAN settings",
		title_wan_txt:"WAN settings",
		title_ap_txt:"AP position settings",
		title_br_txt:"Wireless relay settings",
		set_wan_mode:"WAN access mode",
		
		mode_span_text:" Choose Operation Mode",
		mode_content_notes_text:"Choose the mode you want to configure",
		mode_gw_text:"Gateway Mode",
		mode_br_text:"Repeater Mode",
		mode_wisp_text:"WISP Mode",
		mode_ap_text:"AP Mode",
		
		sys_mode_gw_txt:"Gateway Mode",
		sys_mode_br_txt:"Repeater Mode",
		sys_mode_wisp_txt:"WISP Mode",
		sys_mode_ap_txt:"AP Mode",
		
		set_window_ap:"Location Information",
		lbl_ap_name:"AP Name",
		lbl_ap_location:"AP Location",
		
		gw_one_wan:"First: WAN Settings",
		gw_two_wrl:"Second: Wireless",
		gw_three_over:"Third: Complete",
		gw_three_wrl:"Third：Wireless",
		gw_four_over:"Fourth：Complete",
		gw_wan_static:"Static IP",
		gw_wan_pppoe:"PPPOE(ADSL)",
		gw_wan_dhcp:"DHCP",
		
		status_WAN_IP_Address:"IP Address",
		status_WAN_Subnet_Mask:"Subnet Mask",
		status_WAN_Default_Gateway:"Default Gateway",
		status_WAN_MAC_Address:"MAC",
		lbl_wan_setup_mtu:"MTU",
		lbl_wan_setup_dns21:"Primary DNS",
		lbl_wan_setup_dns22:"Secondary DNS",
		
		lbl_wan_setup_user0:"PPPOE Name",
		lbl_wan_setup_pass0:"PPPOE Password",
		
		dhcp_notes_text:"The current access mode is DHCP,Please click next to configure.",
		adv_dhcp_notes_text:"DHCP access mode, please click on the application configuration.",
		
		wreless25_title:"Wireless Settings",
		wireless2_system_title:"Wireless Settings",
		wireless5_system_title:"5.8G Wireless Settings",
		
		lbl_wireless2_status:"WLAN Status",
		lbl_wireless2_ssid:"SSID",
		lbl_wireless1_Encryption:"Encryption",
		lbl_wireless2_key0:"Key",
		
		lbl_wireless5_status:"5.8GHz WLAN Status",
		lbl_wireless5_ssid:"SSID",
		lbl_wireless5_Encryption:"Encryption",
		lbl_wireless5_key0:"Key",
		
		complete:"Complete Settings",
		ok_txt:"Congratulate，Settings is completed",
		
		br_one_br:"First: Repeater",
		br_two_wrl:"Second: Wireless",
		br_three_over:"Second: Complete",
		
		br_title:"Wireless Repeater",
		br_link_status:"Connection Status",
		br_red_text:"Connect, please later…",
		br_green_text:"Repeater connection is OK",
		status_wreless_select:"Wireless Repeater",
		br_scan_ssid:"Repeater SSID",
		br_scan_Bssid:"BSSID",
		br_scan_SIGNAL:"Signal strength",
		br_scan_CHANNEL:"channel",
		
		adice_name_ap_text:"Signal Strength:",
		adice_name_ap_text:"Encryption:",
		Scan_available_network:"Scan AP",
		
		
		lbl_wireless2_Encryption:"Authentication",
		lbl_wireless2_key0:"Key",
		
		isp_one_br:"First: Repeater",
		isp_two_wan:"Second: WAN",
		isp_three_wrl:"Third: Complete",
		isp_over:"Fourth: Wireless",
		
		window_client_list:"Client List",
		window_dhco_list:"DHCP List",
		window_client_list_mac:"MAC",
		window_client_list_ip:"IP",
		window_client_list_time:"Connection time",
	
		
		ap_one_wrl:"First: Wireless",
		ap_two_lan:"Second：LAN",
		ap_three_over:"Third:Complete",

		
		ap_lan_title:"LAN settings",
		
		adv_title:"Advanced Settings",
		adv_opmode_home:"Return home",
		adv_opmode_main:"Setup Wizard",
		adv_opmode_status:"Device Status",
		adv_opmode_wrl2:"Wireless",
		adv_opmode_wrl5:"5.8G Wireless ",
		adv_opmode_net:"Network",
		adv_opmode_fire:"Firewall",
		adv_opmode_manage:"Management",
		
		
		sec_system_status:"Status",
		sec_wrl2_status:"Wireless Status",
		sec_wrl5_status:"5.8G Wireless Status",
		sec_lan_status:"LAN Status",
		sec_wan_status:"WAN Status",
		
		third_basic_state:"Status",
		adv_software_version:"Software Version",
		adv_hardware_version:"Hardware Version",
		adv_runtime:"Uptime",
		
		third_status_lan:"LAN Status",
		adv_lan_ip:"LAN IP",
		adv_lan_mask:"Subnet Mask",
		adv_lan_mac:"MAC",
		adv_dhcp_server:"DHCP Status",
		adv_dhcp_server_range:"DHCP address range",
		adv_allot_ip:"Assigned IP",
		
		third_status_wan:"WAN Status",
		adv_wan_link_type:"WAN Connect Type",
		adv_wan_ip:"WAN IP",
		adv_wan_mask:"Subnet Mask",
		adv_wan_gateway:"Gateway",
		adv_wan_dns:"DNS",
		adv_status_mac:"MAC",
		
		third_status_wireless2:"wireless connection Status",
		adv_status_wireless2:"Wireless Status",
		third_ap_status_wireless2:"Wireless Status",
		lbl_ssid1:"SSID",
		adv_channel_wireless2:"Channel",
		adv_encrypted_mode_wireless2:"Encryption",
		adv_connected_user_number_wireless2:"Connected Users",
		
		third_status_wireless5:"5.8G wireless connection Status",
		adv_status_wireless5:"5.8G Wireless Status",
		third_ap_status_wireless5:"5.8G Wireless Status",
		adv_broad_wireless5:"SSID",
		adv_channel_wireless5:"Channel",
		adv_encrypted_mode_wireless5:"Encryption",
		adv_connected_user_number_wireless5:"Connected Users",
		set_wireless_mode:"MODE",
		set_rts_wrl2:"RTS Threshold",
		set_ack_timeout_wrl2:"Ack Timeout control",
		set_beacon_wrl2:"Beacon interval",
		set_access_user_wrl2:"MAX User",
		set_ap_threshold_wrl2:"AP threshold",
		set_ampdu_wrl2:"Aggregation",
		set_shortgi_wrl2:"Short GI",
		set_useriso_wrl2:"User isolation",
		wan_mtu_text:"(1400-1500)",
		wan_pppoemtu_text:"(1400-1492)",
		packet_threshold_txt:"(256-2346)",
		packet_rts_txt:"(0-2347)",
		acktimeout_text:"(0-255)us",
		baacon_text:"(100-1024)ms",
		maxuser_text:"(Range 0-64 0 not limited)",
		aprssi_text:" (-95dBm~-65dBm)",
		lbl_wan_dns:"Manually set DNS",
		
		sec_ip_port_filter:"IP/Port Filtering",
		sec_mac_filter:"MAC Filtering",
		sec_url_filter:"URL Filtering",
		sec_port_forward:"Port Forwarding",
		sec_dmz:"DMZ Host",
		
		third_ip_port_set:"IP Filtering Settings",
		set_ip_port:"IP Filtering",
		set_ip_start_fire:"IP ",
		ip_address_range:"IP Address",
		
		third_mac_address_set:"MAC Filtering Settings",
		set_mac_address_filter:"MAC Filtering",
		set_mac_address:"MAC",
		mac_address_font:"MAC",
		
		third_web_url:"URL Filtering Settings",
		set_url:"URL Filtering",
		set_url_address:"URL",
		url_address_span:"URL",
		
		third_Port_forwarding_set:"Port Forwarding",
		Port_forwarding_ip:"IP",
		internal_port:"Internal Port",
		external_port:"External Port",
		port_number:"(1-65535)",
		port_ip_font:"IP",
		port_internal_font:"Internal Port",
		port_external_font:"External Port",
		
		set_dmz_title:"DMZ Settings",
		set_dmz:"DMZ Settings",
		set_dmz_ip:"DMZ LAN IP",
		
		third_sys_time:"System Time",
		third_sys_ddns:"DDNS settings",
		third_qos:"QoS",
		third_sys_log:"Logs",
		third_remove:"Upgrade Firmware",
		third_configure:"System",
		third_usb:"Storage/Server",
		third_user:"User",
		
		sec_usb:"Storage/Server",
		status_usb_name:"DLNA Server name",
		status_usb_server:"Samba Server name ",
		take_usb_text:"Can't find any USB device",
		usb_device_list:"Device List",
		se_sub_name:"Device Name",
		usb_size_font:"Size",
		usb_used_font:"Used",
		usb_available_font:"Available",
		usb_usage_font:"Usage",
		
		
		sec_sys_time:"System Time",
		set_sys_time:"System Time",
		set_time_zone:"Choose Time Zone",
		set_net_time_server:"NTP Server",
		set_Timed_restart:"Equipment timing",
		set_auto_restart:"Auto restart",
		
		sec_set_ddns:"DDNS",
		ddns_text:"Dynamic DNS",
		ddns_user_text:"User Name",
		ddns_pwd_text:"Password/Key",
		ddns_ip_text:"Public IP",
		ddns_dname_text:"Domain",
		ddnstip1:"No account?",
		ddnstip2:"Registration",
		ddnstip3:"Forget password",
		
		sec_qos:"QoS",
		set_qos:"QoS",
		upload_bandwidth_text:"Upload",
		upload_range:"Range:(100-1024000)Kbps",
		download_bandwidth_text:"Download",
		download_range:"Range:(100-1024000)Kbps",
		sec_qos_two:"QoS Rule settings",
		qos_mac_text:"MAC",
		qos_ip_text:"IP range",
		qos_mode:"Mode",
		ipgx_text:"Share total bandwidth with all IP address.",
		ipdx_text:"Assign bandwidth for each IP address.",
		qos_bandwidth_text:"Bandwidth",
		qos_up_text:"Upload",
		qos_down_text:"Download",
		upload_range_d:"Kbps",
		qos_notes_text:"Comment",
		se_notes:"ALL",
		qos_mac_font:"MAC",
		qos_ipstatrt_font:"Start IP",
		qos_ipend_font:"End IP",
		qos_mode_font:"Mode",
		qos_up_font:"Upload(Kbps)",
		qos_down_font:"Download(Kbps)",
		qos_notes_font:"Comment",
		
		sec_log:"System Logs",
		set_log_sys:"Logs",
		lbl_remotely_log_mac:"Remote Log Server",
		lbl_log_ip:"IP",
		lbl_log_port:"Port",
		
		sec_software_upgrade:"Upgrade Firmware",
		set_software_version:"Software Version",
		set_select_file:"Choose File",
		lbl_update_save:"Restore factory settings",
		take_care:"Note",
		take_care_text:"do not power off the device during the upload because it may crash the system!",
		
		sec_backup_restore:"Save/Reload Settings",
		backup_text:"Backup",
		update_text:"Restore",
		restore_default:"Reset Default",
		set_restart:"Reboot",
		
		sec_user_manage:"User",
		old_pwd:"Old Password",
		new_pwd1:"Password",
		new_pwd2:"Confirm Password",
		
		sec_lan_set:"LAN Settings",
		sec_wan_se:"WAN Settings",
		sec_vlan_set:"VLAN",
		sec_wan_senior:"WAN advanced settings",
		third_net_dev_status:"LAN Settings",
		lbl_lan_ip_address:" IP",
		lbl_lan_sub_mask:"Subnet Mask",
		lbl_dhcp_status:"DHCP Status",
		lbl_dhcp_pool_start:"DHCP Client IP Start",
		lbl_dhcp_pool_end:"DHCP Client IP End",
		lbl_lan_lease:"Lease Time(hour)",
		lease_houer:"（1-360）",
		
		third_net_ipmac_status:"IP-MAC Bind",
		lbl_lan_ipmac_text:"IP-MAC Bind",
		
		third_net_dev_vlan:"VLAN",
		vlan_id:"VLAN-ID(3-4094)",
		one:"LAN1",
		two:"LAN2",
		three:"LAN3",
		four:"LAN4",
		five:"WAN",
		w2_1:"AP",
		w2_2:"VAP1",
		w2_3:"VAP2",
		w2_4:"VAP3",
		
		w5_1:"AP",
		w5_2:"VAP1",
		w5_3:"VAP2",
		w5_4:"VAP3",
		
		third_wan_senior:"WAN advanced settings",
		lbl_wan_setup_mac:"MAC clone",
		lbl_wan_mg:"Enable Web Server Access on WAN",
		lbl_wan_mg_port:"Web Port ",
		lbl_wan_unpnp:"Enable uPnP",
		lbl_wan_igmp:"Enable IGMP Proxy",
		lbl_wan_ping:"Enable Ping Access on WAN",
		lbl_wan_ipsec:"Enable IPsec pass through on VPN connection",
		lbl_wan_pptp:"Enable PPTP pass through on VPN connection",
		lbl_wan_l2tp:" Enable L2TP pass through on VPN connection",
		
		sec_wifidog:"Authentication",
		third_wifidog:"Authentication function",
		set_wifidog_text:"Authentication function",
		status_wifidog_port:"Port",
		status_wifidog_ctime:"Client timeout",
		status_wifidog_hostname:"Authentication server",
		status_wifidog_hosthttp:"Authentication server port",
		status_wifidog_src:"Authentication server path",
		lbl_wifidog_block:"External domain white list",
		status_wifidog_black:"External domain white list",
		lbl_wifidog_mac:"MAC White list",
		status_wifidog_mac:"MAC White list",
		wifidog_port_text:"Default 2060, range (1-65535)",
		wifidog_timeout_text:"Default 20 minutes, range (1-65535)",
		wifidog_server_port:"Default 80, range (1-65535)",
		
		sec_cloudset:"Cloud Settings",
		third_cloudset:"Cloud Settings",
		engineering_set:"Debug Setting",
		Engineering_model:"Debug Model",
		lbl_cloudset:"Cloud Server ",
		lbl_yunserver:"Heartbeat Server",
		lbl_yunuser:"Login Name",
		notes_yunuser:"instance:(www.yowifi.net)",		
		
		wan_static_text:"Static IP",
		wan_pppoe_text:"PPPOE(ADSL)",
		wan_dhcp_text:"DHCP",
		
		lbl_wan_setup_mac1:"MAC",
		lbl_wan_setup_dns11:"Primary DNS",
		lbl_wan_setup_dns12:"Secondary DNS",
		
		lbl_wan_setup_mac0:"MAC",
		lbl_wan_setup_dns01:"Primary DNS",
		lbl_wan_setup_dns02:"Secondary DNS",
		
		sec_wrl2_set:"Basic Settings",
		sec_wrl2_brset:"relay settings",
		sec_wrl2_vap_set:"Virtual AP",
		sec_wrl2_adv_set:"Advanced Settings",
		sec_wrl2_adv_mac:"Access Control",
		sec_wrl5_adv_mac:"5.8G Access Control",
		third_wrl2_dev_status:"Wireless Basic Settings",
		third_wrl2_dev_br:"Wireless relay settings",
		lbl_wrl_br_mac:"lockmac",
		lbl_wrl_br_wds:"WDS Passthrough ",
		lbl_wireless_status1:"Wireless Status",
		lbl_ssid1:"SSID",
		wlanHiddenAPDisable:"Disable",
		wlanHiddenAPEnable:"Enable",
		lbl_wlanWMM1:"WMM",
		wlanWMMDisable:"Disable",
		wlanWMMEnable:"Enable",
		third_wrl2_channel:"Channel",
		set_channel_width_wrl2:"Band Width",
		set_channel_wrl2:"Channel",
		third_safe:"Authentication",
		lbl_wls_ap_mode_sel1:"Encryption",
		lbl_wireless_key_val1:"Key",
		
		sec_vap_wrl2:"Virtual AP",
		vap1_txt:"Virtual AP1",
		vap2_txt:"Virtual AP2",
		vap3_txt:"Virtual AP3",
		lbl_wireless_status1:"Wireless Status",
		lbl_ssid1:"SSID",
		lbl_wlanHiddenAP1:"Broadcast SSID",
		wlanHiddenAPDisable:"Disable",
		wlanHiddenAPEnable:"Enable",
		lbl_wlanWMM1:"WMM",
		wlanWMMDisable:"Disable",
		wlanWMMEnable:"Enable",
		third_wrl2_channel:"Channel",
		set_channel_width_wrl2:"Band Width",
		set_channel_wrl2:"Channel",
		third_safe:"Authentication",
		lbl_wls_ap_mode_sel1:"Encryption",
		lbl_wireless_key_val1:"Key",
		
	
		lbl_wireless_status2:"Wireless Status",
		lbl_ssid2:"SSID",
		lbl_wlanHiddenAP2:"Broadcast SSID",
		wlanHiddenAPDisable2:"Disable",
		wlanHiddenAPEnable2:"Enable",
		lbl_wlanWMM2:"WMM",
		wlanWMMDisable2:"Disable",
		wlanWMMEnable2:"Enable",
		lbl_wls_ap_mode_sel2:"Encryption",
		lbl_wireless_key_val2:"Key",
		

		lbl_wireless_status3:"Wireless Status",
		lbl_ssid3:"SSID",
		lbl_wlanHiddenAP3:"Broadcast SSID",
		wlanHiddenAPDisable3:"Disable",
		wlanHiddenAPEnable3:"Enable",
		lbl_wlanWMM3:"WMM",
		wlanWMMDisable3:"Disable",
		wlanWMMEnable3:"Enable",
		lbl_wls_ap_mode_sel3:"Encryption",
		lbl_wireless_key_val3:"Key",
		
		third_advset_wrl2:"Advanced Settings",
		set_output_power_wrl2:"RF Output Power",
		set_ap_threshold_wrl2:"Coverage Threshold",
		
		third_mac_wrl2_set:"Wireless Access Control",
		set_mac_wrl2_filter:"Access Control",
		mac_left_txt:"Access Control List",
		mac_right_txt:"Association STA list",
		
		sec_wrl5_set:"5.8G Basic Settings",
		sec_wrl5_vap_set:"5.8G Virtual AP",
		sec_wrl5_adv_set:"5.8G Advanced Settings",
		third_wrl5_dev_status:"Wireless Basic Settings",
		third_wrl5_channel:"Channel",
		set_channel_width_wrl5:"Band Width",
		set_channel_wrl5:"Channel",
		adv_basic_state:"Encryption",
		sec_vap_wrl5:"5.8G Virtual AP",
		third_advset_wrl5:"5.8G Advanced Settings",
		set_country_code_wrl5:"Regional",
		set_country_code_wrl2:"Regional",
		set_packet_threshold_wrl2:"Packet Threshold",
		set_packet_threshold_wrl5:"Packet Threshold",
		
		set_output_power_wrl2:"RF Output Power",
		set_output_power_wrl5:"RF Output Power",
		set_packet_threshold_wrl5:"Packet Threshold",
		set_packet_threshold_wrl2:"Packet Threshold",
		set_ap_threshold_wrl5:"Coverage Threshold",
		set_ap_threshold_wrl2:"Coverage Threshold",
		
		
		lan_config_text:"LAN",
		status_lan_ip_address:"LAN IP",
		status_lan_mac_address:"MAC",
		wrl2_config_text:"2.4G wireless",
		wrl5_config_text:"5.8G wireless",
		status_wrl2:"Status",
		status_wrl5:"Status",
		status_wrl5_ssid:"SSID",
		status_wrl2_num:"User number",
		lan_conn_type:"Access Type",
		lbl_lan_acaddr:"Manage server IP",
		status_wrl5_num:"User number"
		
		},
	
	BUTTON:{
		flow_btn:"Start Tracking",
		flow_stop_btn:"Stop Tracking",
		
		btn_wifidog_backblock:"Add",
		btn_wifidog_macblock:"Add",
		btn_wifidog_scan:"Scan",
		
		wifi2_btn:"wireless analyzer",
		wifi5_btn:"5G wireless analyzer",
		
		btn_file1:"Upgrade",
		btn_file:"Upgrade",
		
		btn_config_lan:"revise",
		btn_wrl2_client:"Client list",
		btn_wrl5_client:"Client list",
		btn_landhcp_client:"DHCP list",
		
		gw_wan_btn_last:"Back",
		gw_wan_btn_next:"Next",
		
		br_btn_span:"Scan AP",
		btn_br_ap:"Choose AP",
		fire_ip_scan:"Scan",
		qos_mac_scan:"Scan",
		
		update:"Upgrade",
		wrl_mac_import:"Import",
		btn_dmz:"Apply",
		btn_break_bottom:"Refresh",
		btn_system:"Apply",
		btn_vap:"Apply",
		btn_senior:"Apply",
		btn_lan:"Apply",
		btn_vlan:"Apply",
		btn_user_manage:"Apply",
		
		add_btn1_url:"Add",
		delete_btn1_url:"Clear",
		btn_config_fire:"Apply",
		
		//btn_uptime:"Sync with server",
		btn_backup:"Backup",
		btn_restore_default:"Reset Default",
		btn_restart:"Reboot",
		btn_update2:"Restore"
		
		
	},
	//下拉框
	SELECT:{
		
		Key_format64:[
		   
		   {value:"0", 	txt:"ASCII(5 character)"},
		   {value:"1", 	txt:"HEX(10 character)"}
		],
		
		Key_format128:[
		   
		   {value:"2", 	txt:"ASCII(13 character)"},
		   {value:"3", 	txt:"HEX(26 character)"}
		],
		
		net_time_server:[
			{value:"time.windows.com", 	txt:"time.windows.com"},
			{value:"210.98.16.100", 	txt:"210.98.16.100-Time.Kriss.re.kr"},
			{value:"211.115.194.21", 	txt:"211.115.194.21-Ntp1.epidc.co.kr"},
			{value:"64.250.177.145", 	txt:"64.250.177.145-Time.nist.gov"},
			{value:"192.5.41.41", 		txt:"192.5.41.41-North America"},
			{value:"192.5.41.209", 		txt:"192.5.41.209-North America"},
			{value:"208.184.49.9", 		txt:"208.184.49.9-North America"},
			{value:"131.188.3.220", 	txt:"131.188.3.220-Europe"},
			{value:"130.149.17.8", 		txt:"130.149.17.8-Europ"},
			{value:"203.60.1.2", 		txt:"203.60.1.2-Australia"},
			{value:"203.117.180.36", 	txt:"203.117.180.36-Asia Pacific"},
			{value:"custom", 	txt:"---CUSTOM---"}
		],
		
		output_power:[
			{value:"30", 	txt:"100%"},
			{value:"23", 	txt:"75%"},
			{value:"15", 	txt:"50%"},
			{value:"7", 	txt:"25%"},
			{value:"3", 	txt:"12.5%"}
			
		],		
		
		wire_type: [
			{value:1, 	txt:"2.4G"},
			{value:2, 	txt:"5.8G"}
		],
		
		lan_mode: [
			{value:"static", txt:"Static IP "},
			{value:"dhcp", 	txt:"DHCP"}
			
		],
		wan_mode: [
			{value:1, 	txt:"PPPOE(ADSL)"},//PPPoE 用户 (ADSL)
			{value:2, 	txt:"DHCP"},//动态IP 用户 (Cable Modem)
			{value:3, 	txt:"Static IP "}//静态IP 用户
		],
		
		system_status_opmode: [
			{value:1, 	txt:"Gateway Mode"},
			{value:2, 	txt:"WISP"},
			{value:3, 	txt:"Repeater Mode"},
			{value:4, 	txt:"AP Mode"}
		],
		wlan_txpower_mode: [
		{value:0, txt:"Power Saving Mode"},
		{value:1, txt:"Standard Mode"},
		{value:2, txt:"Super Mode"}
		
		],
		Wireless_connection: [
		{value:0, txt:"2.4GHz WIFI"},
		{value:1, txt:"5.8GHz WIFI"},	
		],
		wan1_select:[
			{value:"auto", 	txt:"Auto Mode"},
			{value:"10f", 	txt:"10M Full Duplex"},
			{value:"10h", 	txt:"10M Half-Duplex"},
			{value:"100f", 	txt:"100M Full Duplex"},
			{value:"100h", 	txt:"100M Half-Duplex"}
		],
		
		wireless_country_code:[
			{value:"CN", 	txt:"China" ,title24:"Channel(1-13)",title58:"Channel(36-64),(149-165)"},
			{value:"US", 	txt:"U.S.A" ,title24:"Channel(1-11)",title58:"Channel(36-64),(100-128),(132-140),(149-165)"},
			{value:"BR", 	txt:"Brazil" ,title24:"Channel(1-13)",title58:"Channel(36-64),(100-128),(132-140),(149-165)"},
			{value:"AE", 	txt:"UAE" ,title24:"Channel(1-13)",title58:"Channel(36-64),(100-128),(132-140),(149-165)"},
			{value:"IT", 	txt:"ETSI" ,title24:"Channel(1-13)",title58:"Channel(36-64),(100-128),(132-140)"},
			{value:"IN", 	txt:"India" ,title24:"Channel(1-13)",title58:"Channel(36-64),(149-165)"},
			{value:"DB", 	txt:"Debug" ,title24:"Channel(1-14),(32-44)",title58:"Channel(8-16),(36-64),(100-144),(149-165)"}						
		],
		
		wireless2_mode:[
			
			{value:"11ng", 	txt:"802.11N/G"},
			{value:"11bg", 	txt:"802.11B/G"}
		],
		wireless5_mode:[
			{value:"11a", 	txt:"802.11A"},
			{value:"11na", 	txt:"802.11AN"},
			{value:"11ac", 	txt:"802.11AN/AC"}
			
		],
		
		wireless_mode:[
			{value:"b", 	txt:"802.11B"},
			{value:"g", 	txt:"802.11G"},
			{value:"n", 	txt:"802.11N"},
			{value:"b/g", 	txt:"802.11B/G"},
			{value:"11ng", 	txt:"802.11G/N"},
			{value:"b/g/n", 	txt:"802.11B/G/N"}
		],
		
		wireless2_Bandwidth:[
			{value:"HT20", 	txt:" 20MHz "},
			{value:"HT40", 	txt:" 40MHz  "}
			
		],
		wireless5_Bandwidth:[
			{value:"HT20", 	txt:" 20MHz "},
			{value:"HT40", 	txt:" 40MHz  "},
			{value:"HT80", 	txt:" 80MHz  "}
			
		],
		wireless2_channel:[			   
			{value:0, 	txt:"Auto"},
			{value:1, 	txt:"Channel 1"},
			{value:2, 	txt:"Channel 2"},
			{value:3, 	txt:"Channel 3"},
			{value:4, 	txt:"Channel 4"},
			{value:5, 	txt:"Channel 5"},
			{value:6, 	txt:"Channel 6"},
			{value:7, 	txt:"Channel 7"},
			{value:8, 	txt:"Channel 8"},
			{value:9, 	txt:"Channel 9"},
			{value:10, 	txt:"Channel 10"},
			{value:11, 	txt:"Channel 11"},
			{value:12, 	txt:"Channel 12"},
			{value:13, 	txt:"Channel 13"}
		],
		wireless_channel:[
			{value:0, 	txt:"Auto"},
			{value:1, 	txt:"Channel 1"},
			{value:2, 	txt:"Channel 2"},
			{value:3, 	txt:"Channel 3"},
			{value:4, 	txt:"Channel 4"},
			{value:5, 	txt:"Channel 5"},
			{value:6, 	txt:"Channel 6"},
			{value:7, 	txt:"Channel 7"},
			{value:8, 	txt:"Channel 8"},
			{value:9, 	txt:"Channel 9"},
			{value:10, 	txt:"Channel 10"},
			{value:11, 	txt:"Channel 11"},
			{value:12, 	txt:"Channel 12"},
			{value:13, 	txt:"Channel 13"}
		],
		wireless_base_5_channel_sel:[
			{value:0, 	txt:"Auto"},
			{value:149, 	txt:"Channel 149"},
			{value:153, 	txt:"Channel 153"},
			{value:157, 	txt:"Channel 157"},
			{value:161, 	txt:"Channel 161"},
			{value:165, 	txt:"Channel 165"}
		],
		
		wls_ap_mode_sel: [
			{value:0, 	txt:"none"},
			{value:3, 	txt:"WPAPSK_TKIP"},
			{value:4, 	txt:"WPAPSK_AES"},
			{value:5, 	txt:"WPAPSK_TKIPAES"},
			{value:6, 	txt:"WPA2PSK_TKIP"},
			{value:7, 	txt:"WPA2PSK_AES"},
			{value:8, 	txt:"WPA2PSK_TKIPAES"},
			{value:9, 	txt:"WPA/WPA2PSK_TKIP"},
			{value:10, 	txt:"WPA/WPA2PSK_AES"},
			{value:11, 	txt:"WPA/WPA2PSK_TKIPAES"},
			{value:20, 	txt:"WPA-EAP"}
		],
		wls_br_mode_sel: [
			{value:0, 	txt:"none"},
			{value:3, 	txt:"WPAPSK_TKIP"},
			{value:4, 	txt:"WPAPSK_AES"},
			{value:5, 	txt:"WPAPSK_TKIPAES"},
			{value:6, 	txt:"WPA2PSK_TKIP"},
			{value:7, 	txt:"WPA2PSK_AES"},
			{value:8, 	txt:"WPA2PSK_TKIPAES"},
			{value:9, 	txt:"WPA/WPA2PSK_TKIP"},
			{value:10, 	txt:"WPA/WPA2PSK_AES"},
			{value:11, 	txt:"WPA/WPA2PSK_TKIPAES"},
			{value:20, 	txt:"WPA-EAP"}	
		],
		timezone_sel:[
		    {value:"GMT-4", txt:"UAE"},
			{value:"GMT+5.5", txt:"New Delhi"},
		    {value:"CST-8", 	txt:"Beijing,Chongqing,Urumqi,Re-Hong Kong,Taiwan;"},
			{value:"EST5", 	txt:"(The United States and Canada);Bogota"},			
			{value:"GMT0BST,M3.5.0/1,M10.5.0", 	txt:"GMT;Dublin,Edinburgh,London,Lisbon"},
			{value:"CET-1CEST,M3.5.0,M10.5.0/3", 	txt:"Amsterdam,Berlin,Roma,Stockholm,Paris"},
			{value:"EET-2EEST,M3.5.0/3,M10.5.0/4", 	txt:"Cairo,Athens,Istanbul,Minsk,Jerusalem"},
			{value:"MSK-4", 	txt:"Baghdad,Kuwait,Riyadh,Moscow,Petersburg"},			
			{value:"PKT-5", 	txt:"Yekaterinburg,Islamabad,Karachi,Tashkent"},
			{value:"BDT-6", 	txt:"Alma-Ata,Novosibirsk,Dhaka, Astana"},
			{value:"ICT-7", 	txt:"Bangkok, Jakarta, Hanoi"},			
			{value:"JST-9", 	txt:"Tokyo, Osaka, Sapporo, Seoul, Yakutsk"},
			{value:"EST-10", txt:"Brisbane, Guam, Canberra, Melbourne, Sydney"},
			{value:"MAGT-12", txt:"Magadan, Salomon islands, New Caledonia"},
			{value:"PETT-12", txt:"Fuji, Kamchatka, Marshall Islands, Wellington"},
			{value:"TOT-13", txt:"Nukualofa"}
		],
		time_sel:[
		    {value:"0", 	txt:"0:00"},
			{value:"1", 	txt:"1:00"},			
			{value:"2", 	txt:"2:00"},
			{value:"3", 	txt:"3:00"},
			{value:"4", 	txt:"4:00"},
			{value:"5", 	txt:"5:00"},			
			{value:"6", 	txt:"6:00"},
			{value:"7", 	txt:"7:00"},
			{value:"8", 	txt:"8:00"},			
			{value:"9", 	txt:"9:00"},
			{value:"10",    txt:"10:00"},
			{value:"11",    txt:"11:00"},
			{value:"12",    txt:"12:00"},
			{value:"13", 	txt:"13:00"},			
			{value:"14", 	txt:"14:00"},
			{value:"15", 	txt:"15:00"},
			{value:"16", 	txt:"16:00"},
			{value:"17", 	txt:"17:00"},			
			{value:"18", 	txt:"18:00"},
			{value:"19", 	txt:"19:00"},
			{value:"20", 	txt:"20:00"},			
			{value:"21", 	txt:"21:00"},
			{value:"22",    txt:"22:00"},
			{value:"23",    txt:"23:00"}
		],
		time_day_sel:[
			{value:"day1", 	txt:"one day"},
			{value:"day3", 	txt:"three days"},		
			{value:"day5", 	txt:"Five days"},			
			{value:"day10", txt:"Ten days"}
		],		
		reboot_mode:[
			{value:0, txt:"Every Day"},
			{value:1, txt:"Every Week"},
			{value:2, txt:"One Time"}
		],
		
		input_ipport_select:[
			{value:"", txt:"Disable"},
			{value:"disable", txt:"Black List"},
			{value:"allow", txt:"White List"}
		],
		input_protocol_select:[
			{value:"tcp", txt:"TCP"},
			{value:"udp", txt:"UDP"},
			{value:"tcp+udp", txt:"TCP+UDP"}
		],
		input_url_select:[
			{value:"", txt:"Disable"},
			{value:"disable", txt:"Black List"}
		],
		input_mac_select:[
			{value:"", txt:"Disable"},
			{value:"disable", txt:"Black List"},
			{value:"allow", txt:"White List"}
		],
		input_dmz_select:[
			{value:1, txt:"Disable"},
			{value:2, txt:"Enable DMZ"}
		],
		manage_ddns:[
			{value:1, txt:"Disable"},
			{value:0, txt:"Enable"}
		],
		manage_qos_share:[
			{value:1, txt:"Share"},
			{value:0, txt:"Dedicated"}
		],
		wifi_dog:[
			
			{value:0, txt:"Disable"},
			{value:1, txt:"Enable"}
		],
		wls_mac_mode_list:[
			{value:"", txt:"MAC Access All"},
			{value:"allow", txt:"Allow Listed"},
			{value:"disable", txt:"Deny Listed"}
		]
	},

	JS:{
		//菜单
		login_user:"user",
		login_root:"Admin",
		sta_user_txt:"User name",
		sta_pwd_txt:"Password",
		server_time:"Sync with Server",
		host_time:"Sync with Host",
		flowin:"In tracking......",
		flowout:"cease tracking",
		Tip_wep:"Open WEP encryption mode will cause the device performance decline, determine to open it？",
		Tip_dfs:"Open a key connection, DFS function will be closed!",
		
		
		channel_no:"Channel must be consistent",
		wds_mac:"MAC",
		wds_ssid:"SSID",
		
		ssid_notes_txt:"Maximum not more than 32 characters",
		max32:"Maximum add 32",
		key5:"The password must be 5 characters",
		key10:"The password must be 10 characters",
		key13:"The password must be 13 characters",
		key26:"The password must be 26 characters",
		keyform:"The format is not correct",
		
		err_pwd:"Password error",
		
		dhcp_err:"Address pool settings error",
		
		Cloud_Settings_notes:"Please input Cloud Server Url",
		
		main_wrl2_notes:"2.4G Wireless settings",
		main_wrl2_clients:"2.4G Wireless Client",
		main_wrl5_notes:"5.8G Wireless settings",
		main_wrl5_clients:"5.8G Wireless Client",
		main_lan_clients:"DHCP Client",
		main_lan_notes:"LAN settings",
		main_wan_notes:"WAN settings",
		main_br_notes:"Wireless relay settings",
		main_ap_notes:"AP position settings",
		main_lan_sta_notes:"LAN status",
		main_wl2_sta:"Wireless status",
		main_wl5_sta:"5.8G Wireless status",
		main_wan_sta:"WAN status",
		main_ap_sta:"Wireless AP status",
		main_br_sta:"Wireless relay status",
		
		main_mode_gw_text:"Gateway Mode",
		main_mode_wisp_text:"WISP",
		main_mode_br_text:"Repeater Mode",
		main_mode_ap_text:"AP Mode",
		main_mode_wds_text:"Super WDS",
		hostname:"Host name",
		hostip:"IP",
		hosttime:"Connection time",
		window_client_list_power:"Signal Strength",
		window_client_list:"Client List",
		window_dhco_list:"DHCP List",
		
		
		
		main_wrl_on:"Enable",
		main_wrl_off:"Disable",
		wan_line:"Wan port is not inserted into the network cable, confirmed in the absence of the cable to configure it?",
		restart_btn:"Are you sure to reboot？",
		delete_window_btn:"Are you sure to delete？",
		restart_window_btn:"Are you sure to reboot？",
		restore_window_btn:"Are you sure to reset default？",
		chose_mac:"Please choose MAC！",
		
		day:"Day",
		hour:"H",
		minute:"M",
		second:"S",
		
		dhcp:"DHCP",
		static:"STATIC IP",
		pppoe:"PPPOE",
		
		br_power:"RSS:",
		br_window_Encryption:"Encryption:",
		sacn_channel_name:"Channel:",
		br_Choice_ap:"Choice",
		
		
		main_mode_gw_title:"In this mode,the device is supposed to connect to internet via ADSL/Cable Modem.The nat is enable and PCs in LAN ports share the same IP to ISP through WAN port.The connection type can be setup in WAN page by using PPPOE,DHCP client or static IP.",
		main_mode_br_tiitle:"In this mode, the user can access wireless AP, devices can be connected to other wireless network using the wireless, all interfaces are bridged together. Without NAT, firewall and all network related functions",
		main_mode_wisp_title:"In this mode, all ethernet ports are bridged together and wireless client will connect ISP access point.The NAT is enabled and PCs in ethernet port share the same IP to ISP through wireless LAN.You must set the wireless to client mode first and connect to the ISP AP in Site-Survey page.The connection type can be setup in WAN page by using PPPOE,DHCP client and static IP.",
		main_mode_ap_title:"In this mode, the AP wireless interface and cable interface bridging together. Without NAT, firewall and all network related functions.",
		main_mode_wds_title:"In this mode, the wireless interface can be connected with other wireless AP through WDS, and the wireless interface and cable interface. Without NAT, firewall and all network related functions.",
		
		none:"None",
		
		device_update:"Equipment is being upgraded, please do not cut off",
		save_parameter:"Parameters is saving,please wait……",
		device_restart:"Equipment is restarting,please wait……",
		setup_success:"Set up successfully",
		add_success:"Add success!",
		delete_success:"Delete success!",
		dialup_success:"Dialing is succeed.",
		dial_up:"Dialing...",
		failed_to_dial:"Dialing is failure.",
		up_err:"User or password is error.",
		ip_success:"Get IP address successfully",
		ip_err:"Get IP address failed ",
		ip_loading:"Getting IP address...",
		dns_status:"Check the working status of DNS server...",
		dhcp_no_pppoe:"DHCP mode can not access network,will try PPP0E dial-up.",
		wait_success:"Please wait a moment,to complete your configuration...",
		testing_net:"Internet access is checking...",
		testing_net_err:"The internet connection mode checked is failure",
		testing_net_dhcp:"The current internet access mode checked is dynamic address internet(DHCP)",
		testing_net_pppoe:"The current internet access mode checked is broadband dial-up(PPPOE)",
		please_wait:"Please wait",
		update_please:"Please choose the upgrade file",
		update_err:"File upload failed, please re upload",
		file_loading:"The file is uploading",
		app:"APP is loading,please wait",
		id_err:"Binding ID is failure,please check the internet  connection",
		id_loading:"Binding ID is acquisition",
		abnormal_err:"Exception error",
		set_err:"Set failure",
		choice_time:"Please check in one time at least ！",
		choice_week:"Please check in one week at least！",
		choice_time2:"Please check in one time group at least！",
		logon_failure:"Logon failure！",
		logon_failure_err:"Logon too many times,please wait a moment！",
		max_session:"Maximum session number！",
		success_unloading:"Unloading is success",
		transfer:"Migration is successful",
		format_success:"Format success",
		loading_success:"Loading success",
		message_prompt:"Message prompt",
		message_timeout:"connection timed out",
	
		//验证函数中的错误提示
		suv_nomax:"Rate setting over the maximum range",
		apthreshold:"AP coverage must be between -65 ~ -95",
		maxuser:"Access user number range must be between 0~64",
		beacon:"Beacon frame interval must be between 100~1024",
		acktime:"ACK timeout must be between 0~255",
		rts:"RTS threshold values can not be greater than 2347 or less than 0",
		frag:"The threshold value can not be greater than 2346 or less than 256",
		lease_term:"The lease is not greater than 360 or less than 1",
		vlan_message:"VLAN-ID range 2-4094",
		ip_repeat:"IP address can not be repeated",
		mac_repeat:"MAC address can not be repeated",
		url_repeat:"URL can not repeat",
		rule_repeat:"Rule can not repeat",
		
		need_data:"Please input data",
		exceed_max:"Exceed max lenth,has been automatically shorted",
		comfirm_pwd:"Please input confirm password",
		pwd_differ:"The passwords inputed twice are diferent ",
		non_null_integer:"Please enter a non empty integer again",
		non_numeric_char:"Can not contain non - numeric characters",
		non_null_decimal:"Please enter a non empty decimal again",
		non_decimal_char:"Can not contain other characters except the number and the decimal point",
		digital_format_incorrect:"Digital format is not correct",
		non_null_string:"Please enter a non empty character string again",
		_non_null_string:"Please enter Chinese, English or number",
		not_illegal_char:"Can not contain illegal characters",
		illegal_char:"illegal characters",
		and:"add",
		blank:"blank",
		non_alphanumeric_char:"Can not contain characters other than the number and letters",
		pwd_not_empty:"Password can not be empty",
		pwd_not_empty1:"The password must be numeric or in English and not null",
		not_chinese:"Can not contain Chinese characters",
		server_addr_not_null:"Server address can not be empty",
		discover:"find",
		piece:"individual",
		section:"section",
		the:"The number",
		s_in:"in",
		two:"two",
		three:"three",
		four:"four",
        ip_not_null:"IP address can not be empty",
        ip_val_not_null:"IP value can not be empty",
        ip_range:"IP value can be range 0-255",
        ip_num:"IP address can only be digital",
        ip_broadcast_addr:"IP address can not be brodcast address",
        ip_network_addr:"IP address can not be segment address",
        start_end_ip_err:"Starting IP greater than the end of IP",
		ip_incorrect_len:"IP lenth is not correct", 
		ip_incorrect:"IP is illegal",
        ip_reserve_addr:"IP address can not be reserved address",
		not_loopback_addr:"IP address can not be loopback address",
		not_multicast_addr:"IP address can not be multicast address",
        not_lan_ip_addr:"IP address can not be the same as router address",
        not_lan_mask_addr:"IP address can not be subnet mask address",
		firsr_section_not_zero:"IP first can not be 0",
        four_section_not_zero:"IP fourth can not be 0",
		ip_one_net:"IP scope is required to be in the same segment",
		ip_norepeter:"IP range can not be repeated",
		ip_gw_norepeter:"The IP address is not the same as the default gateway",
		ip_gw_noaddress:"The IP address and the default gateway should be in the same segment!",
		gwip_ip_noaddress:"The IP network and the IP network can not be in the same segment!",

        getway_not_null:"Default gateway can not be empty",
        getway_val_not_null:"Default gateway can not be empty",
        getway_range:"Default gateway can only be range 0-255",
        getway_num:"Default gateway can only be numbers",
        getway_broadcast_addr:"Default gateway can not be brodcast address",
        getway_network_addr:"Default gateway can not be destination",
        getway_incorrect_len:"The length of default gateway is not correct",
        getway_incorrect:"Default gateway is illegal",
        getway_reserve_addr:"Default gateway can be reserved address",
        getway_not_loopback_addr:"Default gateway can not be loopback address ",
        getway_not_multicast_addr:"Default gateway can not be multicast address",
        not_lan_getway_addr:"Default gateway can not be the same as router address",
        getway_not_lan_mask_addr:"Default gateway can not be subnet mask address",
        getway_firsr_section_not_zero:"Default gateway first can not be 0",
        getway_four_section_not_zero:"Default gateway fourth can not be 0",

		dns_not_null:"DNS can not be empty",
		dns_format_incorrect:"DNS format is not correct",
		outtime_not_null:"Timeout period can not be empty",
		outtime_non_numeric_char:"Timeout time can not contain non numeric characters",
		outtime_range:"Timeout period can not be greater than 65535 or less than 1",
		port_not_null:"Port can not be empty",
		start_end_port_err:"The start port is greater than the end port",
		port_non_numeric_char:"Ports cannot contain non - numeric characters",
		port_range:"Ports can not be more than 65535 or less than 1",
		mask_err:"Subnet mask input error",
		mask_format_err:"Subnet mask does not conform to the specification",
		mac_err:"MAC address is error",
		mac_not:"MAC address can not be empty",
		mac_norepeter:"MAC can not repeat",
        mac_broadcast_addr:"MAC address can not be multicaste address",
		mtu_1500_1400:"MTU value can not be more than 1500 or less than 1400",
		mtu_1500_576:"MTU value can not be more than 1500 or less than 576",
		mtu_1480_576:"MTU value can not be more than 1492 or less than 1400",
		mtu_1440_576:"MTU value can not be more than 1440 or less than 576",
		pppoe_out_time_range:"Timeout should be between 1 and 30.",
		year_lt_2008:"The year can not be less than 2008",
		month_range:" The month range from 1-12",
		day_range:" The date range from 1-",
		hour_range:"The hour range from 0-23",
		minute_range:"The minute range from 0-59",
		second_range:"The second rangge from 0-59",
		calendar_not_null:"The date can noe be empty",
		calendar_format_err:"Date format is not cor",
		year_err:"Year inputed is not correct",
		month_err:"Month inputed is not correct",
		day_err:"Date inputed is not correct",
		url_not_null:"Please enter a none empty URL",
		url_err:"URL is not correct",
		eq_5:"Please enter 5 characters",
		eq4_20:"Please enter 4-20 characters",
		eq6_20:"Please enter 6-20 characters",
		eq8_63:"Please enter 8-63 characters",
		eq8_30:"Please enter 8-30 characters",
		pwd_low:"weak",
		pwd_medium:"medium",
		pwd_strong:"strong",
		whole_day:"disable",
		week:"week",
		day0:"Monday",
		day1:"Tuesday",
		day2:"Wednesday",
		day3:"Thursday",
		day4:"Friday",
		day5:"Saturday",
		day6:"Sunday"
	}
};

$(document).attr("title","HIGH PERFORMANCE INTELLIGENT WIRELESS OUTDOOR	CPE/AP");
//other



